name = "HNSW"
uuid = "540f64fa-c57e-11e8-081c-41422cda4629"
authors = ["Jonas Isensee <jonas.isensee@web.de>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[targets]
test = ["Test", "NearestNeighbors", "StaticArrays"]
